
public enum TipoExame {
    COLONOSCOPIA,
    DESINTOMETRIA_OSSEA,
    ELETROCARDIOGRAMA,
    ERGOMETRIA,
    HEMOGRAMA,
    MAMOGRAFIA,
    RAIO_X,
    TOMOGRAFIA,
    ULTRASSONOGRAFIA,
    URINA
}
